# Generated by Django 4.2.13 on 2024-11-19 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_build', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifierInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(max_length=30)),
                ('classifier_model', models.CharField(max_length=30)),
                ('classifier_scaler', models.CharField(max_length=30)),
                ('accuracy', models.CharField(max_length=30)),
                ('f1score', models.CharField(max_length=30)),
                ('precision', models.CharField(max_length=30)),
                ('recall', models.CharField(max_length=30)),
            ],
        ),
    ]
